version: '3'

services:
  mydb:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

 
